review
tammaco/slozhno-sosredotochitsya pull request #1
Opened 2024-08-01 17:17 UTC by tammaco

2024-08-02 09:55 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Здравствуйте! У вас получилась хорошая работа. _Пожалуйста, не торопитесь, и после исправления проверяйте исправление всех критических комментариев и соответствие макету на всех брейкпоинтах._


_Что понравилось:_


- работают темы и автотемы
- Правильное форматирование
- Корректная структура HTML
- У всех интерактивных элементов есть ховер эффект
- У всех интерактивных элементов есть состояние фокуса
- Валидный код
- отличная структура файлов проекта
- Хорошая семантика
- Хорошие стили 
- Отзывчивая верстка
- Сетка гибко реагирует на изменение контента
- Похоже на макет на брейк-поинтах


_Что необходимо исправить:_

- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично». А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

- `1, 2, first, second и т.д` порядковые числительные не следует применять  в названиях, т.к. порядок или числовое значение может измениться. Нужно переименовать все подобные классы


- При **любой ширине экрана блоки header и footer** должны иметь высоту, равную высоте экрана, например **100vh**:
   - https://disk.yandex.ru/i/sllJVBPYFPE9-g
   - https://disk.yandex.ru/i/FmcS0oEsp60F-Q


- Одинаковые свойства в разных медиазапросах не должны дублироваться. В каждом медиазапросе должны быть описаны только те стили, которые отличаются от другого медиазапроса. Если правило определенно для основного блока, так же нет необходимости его дублировать в медиазапросе, так как оно будет наследоваться. Для удобства можно воспользоваться поиском в файле по строке



- https://disk.yandex.ru/i/3CehpbqJD1jhPA у этих заголовков(именно у пяти, не включая сверху) не должно быть жирного шрифта на всех ширинах экрана


- **При исправлении для одной из тем (светлой/тёмной) обязательно проверяйте, чтобы при такой же автотеме (светлой/тёмной) было соответствующее исправление.** Это напоминалка, а не конкретное исправление.



- при светлых темах(проверяйте и на авто-светлой и светлой теме) при любой ширине экрана:
  - https://disk.yandex.ru/i/SvuQnZUA_EpV-A не тот цвет тени заголовка футера





- Есть случаи, когда  нужно подправить верстку между точек останова. Для некоторых элементов нужно поменять стили и/или диапазон ширин брейкпоинтов в медиаправилах. Примеры: 
 - между брейкпоинтов 375px и 768px:
   -  https://disk.yandex.ru/i/WNeUdzfN-YPx6g картинки должны быть на всю ширину только с отступами от краёв экрана и увеличиваться пропорционально ширине экрана




 -  При ширине страницы более 1024px (или 1440px, как изначально в global.css) должны прибавляться только края:
     -   https://disk.yandex.ru/i/gWDgLVT-NZwmyA  контент должен быть по центру по горизонтали



- Для ширины экрана 1024px _не совпадает с макетом_ :
  -    размер и выравнивание кнопок в хедере
  -    https://disk.yandex.ru/i/wHjw8lUXiI3cQw выравнивание элементов в футере

- Для ширины экрана 768px _не совпадает с макетом_ : 
  -    размер и выравнивание кнопок в хедере
  -    выравнивание тех же элементов в футере

- При ширине экрана 375px  _не совпадает с макетом_:
  -    размер и выравнивание кнопок в хедере
  -   https://disk.yandex.ru/i/3PgdPbJvTFQhOQ  отступ под заголовком в секции галерея



_Что можно улучшить:_

- Все комментарии с пометкой "Можно лучше"
- CSS-правила в коде желательно распологать в примерном соответствии с позицией элементов html
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- Можно использовать `transition` для более плавных переходов Hover эффектов. Это улучшает визуальное восприятия. Для работы `transition` сразу на наведение и на снятие нужно указать его к самому селектору, а не к hover этого селектора
- Для единообразного форматирования документов в VSCode лучше положить файл `.editorconfig` в корневой каталог. Файл .editorconfig это файл для единого формата редактирования во всех языках, который поддерживает большинство IDE, что бы не нужно было в каждом новом проекте/языке  настраивать форматирование документов, а просто класть этот файлик в корень проекта. Ссылки по теме:
  - https://habr.com/ru/articles/220131/
  - https://editorconfig.org/
  - Пример файла https://disk.yandex.ru/d/Q7mSEMV3ua23Qg


- А так же можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`



**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +.header__lamp {
https://disk.yandex.ru/i/O4Tc-jI4l5pU8g Насыщенность шрифта должна быть 400

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +.header {
- При **любой ширине экрана блоки header и footer** должны иметь  высоту равную высоте экрана, например **100vh**, а так же нужно дополнительно указать для страницы нужно указать минимальную высоту блока по макету или самым минимальным значением(668px) что бы блок не мог слишком сжаться

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +.footer {
- При **любой ширине экрана блоки header и footer** должны иметь  высоту равную высоте экрана, например **100vh**, а так же нужно дополнительно указать для страницы нужно указать минимальную высоту блока по макету или самым минимальным значением(668px) что бы блок не мог слишком сжаться

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +.corner-frames::before {
Толщина линий должна быть по 1px

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +.corner-frames::after {
Толщина линий должна быть по 1px

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +  font-family: var(--main-font, sans-serif);
---

**Можно лучше:**


  - **Это  моноширинный шрифта, тип альтернативного браузерного шрифта для каждого св-ва font-family используйте значение monospace**  https://doka.guide/css/font-family/#znacheniya

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +  position: absolute;
Для абсолютного позиционирования используют координаты, css свойства top, bottom, left, right

Для корректного позиционирования элемента нужно задать выравнивание **минимум по одной оси, вертикальной и/или горизонтальной**, или в некоторых браузерах этот элемент может отображаться некорректно. А так же не стоит позиционировать подобный элемент через margin/padding вместо координат.

Подробнее: https://developer.mozilla.org/ru/docs/Web/CSS/position

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +@media (375px <=width <768px) {
---

**Можно лучше:**

Не следует использовать медиазапросы между двумя точками, не используйте ключевое `and` для `@media` такой подход приводит к тому что стили, написанные между точками, не наследуются и получается что приходится дублировать код. 

В данном случае можно просто убрать нижнюю границу ширин

Будет более точным вариантом:

Например, Технология `mobile first`

- основные селекторы(не в медиазапросах содержат правила для точки 375px и выше), далее 
- `@media (width >= 768px)`  правила для 768px и выше
- `@media (width >= 1024px)`  правила для 1024 и выше

или

Технология `desktop first`

- основные селекторы(не в медиазапросах содержат правила для точки 1024 и ниже), а медиазапросы идут в обратную сторону относительно примера `mobile first`

После исправления нужно будет внимательно проконтролировать соответствие проекта макету, и корректное отображение между брейкпоинтов

2024-08-02 09:55 UTC, Avaakum commented on styles/variables.css
> +@media (prefers-color-scheme: dark) {
- Это медиа правило нужно переместить в файл dark.css

---

**Можно лучше:**

- Это лишнее медиа правило.  Эти стили для авто-темы по умолчанию желательно задать только в файле  variables, без медиа выражения, а для другой авто-темы уже будет использовать медиа выражение.


---

Мы изначально выбираем одну тему как основную(тёмную или светлую), и страница должна корректно отображаться при выборе авто-темы с той, которой мы задавали как основную.

  -   Например, если мы решили использовать умолчанию тему и авто-тему тёмную(эту тему мы как раз указываем в html в метатеге первой),
  - то в файле variables определяем все переменные  под тёмную тему для селектора `:root`, а фон для страницы и отображение  rec и если есть другие отличия добавляем в style.css.
  - Далее в файле тёмной темы для класса тёмной темы нужно копировать все эти стили: значения переменных, отображение rec и фон страницы.
  - При включении светлой темы применяются значения переменных от класса светлой темы, которые должны быть определены в файле  light.css. А при включении авто-темы "светлой" уже  будет использовано медиа правило ` prefers-color-scheme: light ` из этого же файла, в котором дублируются стили от светлой темы, только уже не для класса, а для селектора `:root`, плюс остальные моменты, как показ rec и прочее

2024-08-02 09:55 UTC, Avaakum commented on styles/variables.css
> +@media (prefers-color-scheme: light) {
Это лишнее медиа правило, подобные значения для авто-светлой темы уже заданы в файле light.css

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +    <meta name="color-scheme" content="dark light">
---

**Отлично:**

Цветовые схемы описаны в теге

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +    <link rel="stylesheet" href="./fonts/fonts.css">
---

**Отлично:**

Правильный порядок подключения стилей. Шрифты должны быть подключены первыми, потом общие стили(сброс), потом кастомные. При таком порядке подключении шрифты могут быть использованы в двух последующих файлах.  А так же сброс стилей должен быть до подключения своих стилей из-за специфики CSS, чтобы `global.css` не переопределил никаких наших стилей.

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +      <section class="content__section section_1">
- `1, 2, first, second и т.д` порядковые числительные не следует применять  в названиях, т.к. порядок или числовое значение может измениться. Нужно переименовать все подобные классы

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +    <main class="content">
---

**Можно лучше:**

Для стилизации будет лучше использовать вложенные селекторы и вспомогательные классы

Пример реализации

```

Для секций

.section { ...Общие стили секций(тип сетки, gap и так далее) }

.section-why {}

.section-causes {}

.section-advices {}


Например для списков/обёрток карточек в случае если сетка списков разная

.section-why .list {}

.section-causes .list {}

.section-advices .list {}


Например для списков/обёрток карточек в случае если **часть** сетки/стилей списков однотипна

.list { color: #000; }

.section-causes .list { color: #fff; }

 
```

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +          <article class="content__section-item">
---

**Отлично:**

Отличная семантика

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +            <h3 class="title-decor content__section-item__subtitle">
- Уровень заголовка не соответствует структуре страницы. Тут  и далее в секции будут h4. Заголовок выше озаглавливает эти разделы

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +          <h3 class="title-decor content__section-subtitle">
---

**Отлично:**

 Этот заголовок ниже уровнем чем секции, но выше чем, следующие заголовки из подразделов, которые он озаглавливает, тут должен быть h3

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +      <p class="footer-title">focus</p>
---

**Можно лучше:**

 Это такой же заголовок как в хедере, но h1 уже занят

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +            loading="lazy"
---

**Отлично:**

Есть атрибуты для отложенной загрузки изображений

2024-08-02 09:55 UTC, Avaakum commented on index.html
> +            <p class="content__section-item__paragraph">
---

**Можно лучше:**



Для удобства и расширения/изменения контента страницы в будущем желательно подготавливать под это удобную структуру html. В данном случае, в каждой секции можно выделять общий контейнер для всех подразделов этой секции(отдельно в секции "Как концентрироваться лучше" это будет ещё отдельный див для подразделов после второго заголовка секции или под это дело можно добавить список ul при желании), и выравнивать эти подразделы уже внутри одного контейнера, что гораздо проще чем строить более сложную грид сетку.

А для параграфов, даже если это пока только один параграф, можно так же в каждом подразделе ещё добавлять div, и задавать этому div отступ например через flex gap. Тогда при добавлении новых параграфов в любом подразделе сразу прибавится корректный отступ.


---


Выше, это общая рекомендация для улучшения структуры html, для возможного масшатабирования проекта. При создании адаптивной вёрстки лучше сразу представлять где может изменяться и дополняться контент, так как банально проект может быть посажен на CMS и потом редактироваться уже не разработчиками. Например, в текстовом подразделе всегда может дополниться количество подразделов и/или количество параграфов этого подраздела и желательно, что бы вёрстка под это подстраивалась и не ломалась. Современные технологии сеток хорошо под это заточены. 
Так же под это желательно использовать семантику HTML5, что бы страницу лучше воспринимали поисковые системы (списки, article, section, figure, nav... ) и в совокупности получаются уже сразу готовые конструкции, которые удобно использовать для адаптивной вёрстки, как например  внутри последней текстовой секции ` section.section.how>h2+article>h3+ul>(li>h4+div>p+p)*4`  (сокращение для расширения Emmet)

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +    grid-template-rows: 23px auto;
**Надо исправить**
Правило grid-template-rows с жёсткими значениями нужно удалить. Нет необходимости высчитывать высоту ячеек, так как само содержимое ячейки определяет её текущую высоту. Использование жёстких значений для высоты ячеек может привести к проблемам с адаптивностью и усложнить поддержку кода.

2024-08-02 09:55 UTC, Avaakum commented on styles/style.css
> +    inline-size: 355px;
Лишний стиль, при корректном выравнивании все изображения будут совпадать с макетом и хорошо отображаться между брейкпоинтов

2024-08-02 20:59 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Желаю вам удачи в следующих спринтах и проектах! 

---

_Что необходимо исправить:_

- **Неисправленные комментарии в коде с прошлой итерации, кроме "можно лучше" и "отлично" . А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**


- При **любой ширине экрана блоки header и footer** должны иметь высоту, равную высоте экрана, например **100vh**:
   - https://disk.yandex.ru/i/sllJVBPYFPE9-g
   - https://disk.yandex.ru/i/FmcS0oEsp60F-Q
 
- Одинаковые свойства в разных медиазапросах не должны дублироваться. В каждом медиазапросе должны быть описаны только те стили, которые отличаются от другого медиазапроса. Если правило определенно для основного блока, так же нет необходимости его дублировать в медиазапросе, так как оно будет наследоваться. Для удобства можно воспользоваться поиском в файле по строке

- при светлых темах(проверяйте и на авто-светлой и светлой теме) при любой ширине экрана:
  - https://disk.yandex.ru/i/SvuQnZUA_EpV-A не тот цвет тени заголовка футера

- В проекте есть нарушения в отображении по макету их нужно нужно проконтролировать самостоятельно и исправить
  - Для более точного контроля отображения вёрстки можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi  )  для `Chrome`, можно в фигме выделить весь макет, экспортировать его картинкой и наложить на вёрстку в браузере. Плагин позволяет наложить изображение на вёрстку в браузере, тем самым можно с легкостью подправить недочёты по отображению. А так же, если включить в расширении инверсию цвета и прозрачность 50%, то соответствие по пикселям и цветам видно лучше, так как при сложении цветов получается однородный серый цвет.

---




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 


Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2024-08-05 10:05 UTC, tammaco commented
777

2024-08-05 10:31 UTC, merged